name: pull request

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.x' # set this to the dot net version to use

jobs:
  validate:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: |
        dotnet restore ./src/HaveIBeenPwned.Client.Abstractions/HaveIBeenPwned.Client.Abstractions.csproj
        dotnet restore ./src/HaveIBeenPwned.Client/HaveIBeenPwned.Client.csproj
        dotnet restore ./src/HaveIBeenPwned.Client.PollyExtensions/HaveIBeenPwned.Client.PollyExtensions.csproj
      
    - name: Build
      run: |
        dotnet build ./src/HaveIBeenPwned.Client.Abstractions/HaveIBeenPwned.Client.Abstractions.csproj --configuration Release --no-restore
        dotnet build ./src/HaveIBeenPwned.Client/HaveIBeenPwned.Client.csproj --configuration Release --no-restore
        dotnet build ./src/HaveIBeenPwned.Client.PollyExtensions/HaveIBeenPwned.Client.PollyExtensions.csproj --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test ./src/HaveIBeenPwned.Client.AbstractionsTests/HaveIBeenPwned.Client.AbstractionsTests.csproj --verbosity normal
        dotnet test ./src/HaveIBeenPwned.ClientTests/HaveIBeenPwned.ClientTests.csproj --configuration Release --verbosity normal
        dotnet test ./src/HaveIBeenPwned.Client.PollyExtensionsTests/HaveIBeenPwned.Client.PollyExtensionsTests.csproj --verbosity normal
