name: pull request

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '5.0.x' # set this to the dot net version to use

jobs:
  validate:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: |
        cd ./src/HaveIBeenPwned.Client
        dotnet restore
      
    - name: Build
      run: |
        cd ./src/HaveIBeenPwned.Client
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd ./tests/HaveIBeenPwned.ClientTests
        dotnet test --no-restore --verbosity normal
